In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import unicodedata
import numpy as np
import unicodedata



df = pd.read_csv("statelist2024.csv") # fuente Kaggle
df.columns.tolist
df.head(1000)
print(df.columns.tolist) 

df_ico_modernos = df[[ 'statenme','stateabb', 'styear','endyear']]
df_ico_modernos.head()

<bound method IndexOpsMixin.tolist of Index(['stateabb', 'ccode', 'statenme', 'styear', 'stmonth', 'stday',
       'endyear', 'endmonth', 'endday', 'version'],
      dtype='str')>

                   statenme stateabb  styear  endyear
0  United States of America      USA    1816     2024
1                    Canada      CAN    1920     2024
2                   Bahamas      BHM    1973     2024
3                      Cuba      CUB    1902     1906
4                      Cuba      CUB    1909     2024

Vemos que "Soviet_Union" y "Serbia y Montenegro" no tienen codigo ICO_modern_aqui

In [2]:
df_ico_modernos.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statenme  244 non-null    str
 1   stateabb  244 non-null    str
 2   styear    244 non-null    int64
 3   endyear   244 non-null    int64
dtypes: int64(2), str(2)
memory usage: 7.8 KB

In [3]:
def tipos_por_columna(df):
    for col in df.columns:
        print(f"\n--- {col} ---")
        print(df[col].apply(lambda x: type(x).__name__).value_counts())
tipos_por_columna(df)

--- stateabb ---
stateabb
str    244
Name: count, dtype: int64

--- ccode ---
ccode
int    244
Name: count, dtype: int64

--- statenme ---
statenme
str    244
Name: count, dtype: int64

--- styear ---
styear
int    244
Name: count, dtype: int64

--- stmonth ---
stmonth
int    244
Name: count, dtype: int64

--- stday ---
stday
int    244
Name: count, dtype: int64

--- endyear ---
endyear
int    244
Name: count, dtype: int64

--- endmonth ---
endmonth
int    244
Name: count, dtype: int64

--- endday ---
endday
int    244
Name: count, dtype: int64

--- version ---
version
int    244
Name: count, dtype: int64

In [4]:
print(df_ico_modernos.info())
print("-------")
print(df_ico_modernos.nunique())   # no los voy a eliminar , los quiero asi
df_ico_modernos.head()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statenme  244 non-null    str
 1   stateabb  244 non-null    str
 2   styear    244 non-null    int64
 3   endyear   244 non-null    int64
dtypes: int64(2), str(2)
memory usage: 7.8 KB
None
-------
statenme    218
stateabb    218
styear       94
endyear      28
dtype: int64

                   statenme stateabb  styear  endyear
0  United States of America      USA    1816     2024
1                    Canada      CAN    1920     2024
2                   Bahamas      BHM    1973     2024
3                      Cuba      CUB    1902     1906
4                      Cuba      CUB    1909     2024

In [5]:
lista_columnas_ico_modernos = df_ico_modernos.columns.to_list() # la quiero para otra cosa
lista_columnas_ico_modernos

['statenme', 'stateabb', 'styear', 'endyear']

In [6]:
df_ico_modernos.to_csv("Codigos_ICO_Modernos.csv", index= False)