In [31]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import unicodedata
import numpy as np
import unicodedata


df_campeones = pd.read_csv("Campeones_Copa_Europa_Euroleague.csv")
df_ico_modernos = pd.read_csv("Codigos_ICO_Modernos.csv")
df_ico_antiguos= pd.read_csv("Codigos_ICO_Antiguos.csv")

In [32]:

print(df_campeones.columns)
df_campeones.head()

Index(['year_win', 'team', 'statenme'], dtype='str')

   year_win                  team      statenme
0      1958         A. S. K. Riga  Soviet Union
1      1959         A. S. K. Riga  Soviet Union
2      1960         P. B. K. CSKA  Soviet Union
3      1961  B. C. Dinamo Tbilisi  Soviet Union
4      1962         P. B. K. CSKA  Soviet Union

In [33]:
columnas_originales = df_campeones.columns
columnas_finales = ["year_win","team", "statenme"]
diccionario_cambio_campeones = dict(zip(columnas_originales,columnas_finales))
df_campeones.rename(columns=diccionario_cambio_campeones, inplace=True)
df_campeones.head()

   year_win                  team      statenme
0      1958         A. S. K. Riga  Soviet Union
1      1959         A. S. K. Riga  Soviet Union
2      1960         P. B. K. CSKA  Soviet Union
3      1961  B. C. Dinamo Tbilisi  Soviet Union
4      1962         P. B. K. CSKA  Soviet Union

A ver ahora la tabla de ico modernos veo un poco las tablas

In [34]:
print(df_ico_modernos.columns)
df_ico_modernos.head(20)

Index(['statenme', 'stateabb', 'styear', 'endyear'], dtype='str')

                          statenme stateabb  styear  endyear
0         United States of America      USA    1816     2024
1                           Canada      CAN    1920     2024
2                          Bahamas      BHM    1973     2024
3                             Cuba      CUB    1902     1906
4                             Cuba      CUB    1909     2024
5                            Haiti      HAI    1859     1915
6                            Haiti      HAI    1934     2024
7               Dominican Republic      DOM    1894     1916
8               Dominican Republic      DOM    1924     2024
9                          Jamaica      JAM    1962     2024
10             Trinidad and Tobago      TRI    1962     2024
11                        Barbados      BAR    1966     2024
12                        Dominica      DMA    1978     2024
13                         Grenada      GRN    1974     2024
14                       St. Lucia      SLU    1979     2024
15  St. Vincent and the Grenadines      SVG    1979     2024
16               Antigua & Barbuda      AAB    1981     2024
17             St. Kitts and Nevis      SKN    1983     2024
18                          Mexico      MEX    1831     2024
19                          Belize      BLZ    1981     2024

A ver ahora la tabla de ico antiguas veo un poco las tablas

In [35]:
print(df_ico_antiguos.columns)
df_ico_antiguos.head()

Index(['Código', 'Federación nacional', 'desde', 'hasta'], dtype='str')

  Código          Federación nacional  desde  hasta
0    AHO         Netherlands Antilles   1960   2008
1    AIN  Neutral Individual Athletes   2024   2026
2    ANZ              Australasia ANZ   1908   1912
3    BIR                        Burma   1948   1988
4    BOH                      Bohemia   1900   1912

Le cambio columnas a esta tabla para unirlas luego en ingles

In [36]:
columnas_originales = df_ico_antiguos.columns
columnas_finales = ["stateabb","statenme", "styear", "endyear"]
diccionario_cambio_campeones = dict(zip(columnas_originales,columnas_finales))
df_ico_antiguos.rename(columns=diccionario_cambio_campeones, inplace=True)
df_ico_antiguos.head()

  stateabb                     statenme  styear  endyear
0      AHO         Netherlands Antilles    1960     2008
1      AIN  Neutral Individual Athletes    2024     2026
2      ANZ              Australasia ANZ    1908     1912
3      BIR                        Burma    1948     1988
4      BOH                      Bohemia    1900     1912

In [37]:
df_union_icos = pd.concat([df_ico_antiguos, df_ico_modernos], ignore_index=True, sort=False)
df_union_icos.head(1000
                   )

    stateabb                        statenme  styear  endyear
0        AHO            Netherlands Antilles    1960     2008
1        AIN     Neutral Individual Athletes    2024     2026
2        ANZ                 Australasia ANZ    1908     1912
3        BIR                           Burma    1948     1988
4        BOH                         Bohemia    1900     1912
..       ...                             ...     ...      ...
285      NAU                           Nauru    1999     2024
286      MSI                Marshall Islands    1991     2024
287      PAL                           Palau    1994     2024
288      FSM  Federated States of Micronesia    1991     2024
289      WSM                           Samoa    1976     2024

[290 rows x 4 columns]

In [38]:
df_union_icos["styear"] = pd.to_numeric(df_union_icos["styear"], errors="coerce").astype("Int64")
df_union_icos["endyear"] = pd.to_numeric(df_union_icos["endyear"], errors="coerce").astype("Int64")

cols_texto = df_union_icos.select_dtypes(include="object").columns
df_union_icos[cols_texto] = df_union_icos[cols_texto].fillna("")

C:\Users\ernes\AppData\Local\Temp\ipykernel_35292\79395656.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols_texto = df_union_icos.select_dtypes(include="object").columns

In [39]:
df_union_icos= df_union_icos.sort_values("statenme")
print(df_union_icos.shape)
df_union_icos.head()

(290, 4)

    stateabb     statenme  styear  endyear
243      AFG  Afghanistan    1919     2024
132      ALB      Albania    1944     2024
131      ALB      Albania    1914     1939
218      ALG      Algeria    1962     2024
99       AND      Andorra    1993     2024

Ahora aplico una columna a la tabla campeones donde añado el codigo y la nota segun el año

In [40]:
lista_paises_campeones= df_campeones["statenme"].unique().tolist() 
for x in lista_paises_campeones:
    print(f"{x}: {x in df_union_icos['statenme'].values}")

Soviet Union: True
Spain: True
Italy: True
Israel: True
Yugoslavia: True
Serbia and Montenegro: True
France: True
Greece: True
Lithuania: True
Russia: True
Turkey: True

! Estan todos en la lista!

In [41]:
df_union_icos.head()

    stateabb     statenme  styear  endyear
243      AFG  Afghanistan    1919     2024
132      ALB      Albania    1944     2024
131      ALB      Albania    1914     1939
218      ALG      Algeria    1962     2024
99       AND      Andorra    1993     2024

Vamos por fin a unirlo con df_campeones

In [42]:
df_campeones.head()

   year_win                  team      statenme
0      1958         A. S. K. Riga  Soviet Union
1      1959         A. S. K. Riga  Soviet Union
2      1960         P. B. K. CSKA  Soviet Union
3      1961  B. C. Dinamo Tbilisi  Soviet Union
4      1962         P. B. K. CSKA  Soviet Union

In [43]:
df_tabla_final = df_campeones.merge(
    df_union_icos,
    on="statenme",
    how="left"
)
df_tabla_final.head(20)

    year_win                    team      statenme stateabb  styear  endyear
0       1958           A. S. K. Riga  Soviet Union      URS    1952     1988
1       1959           A. S. K. Riga  Soviet Union      URS    1952     1988
2       1960           P. B. K. CSKA  Soviet Union      URS    1952     1988
3       1961    B. C. Dinamo Tbilisi  Soviet Union      URS    1952     1988
4       1962           P. B. K. CSKA  Soviet Union      URS    1952     1988
5       1963  Real Madrid Baloncesto         Spain      SPN    1816     2024
6       1964  Real Madrid Baloncesto         Spain      SPN    1816     2024
7       1965            P. O. Milano         Italy      ITA    1816     2024
8       1966  Real Madrid Baloncesto         Spain      SPN    1816     2024
9       1967  Real Madrid Baloncesto         Spain      SPN    1816     2024
10      1968           P. B. K. CSKA  Soviet Union      URS    1952     1988
11      1969    Pallacanestro Varese         Italy      ITA    1816     2024
12      1970           P. B. K. CSKA  Soviet Union      URS    1952     1988
13      1971    Pallacanestro Varese         Italy      ITA    1816     2024
14      1972    Pallacanestro Varese         Italy      ITA    1816     2024
15      1973  Real Madrid Baloncesto         Spain      SPN    1816     2024
16      1974    Pallacanestro Varese         Italy      ITA    1816     2024
17      1975    Pallacanestro Varese         Italy      ITA    1816     2024
18      1976  Maccabi Tel Aviv B. C.        Israel      ISR    1948     2024
19      1977  Real Madrid Baloncesto         Spain      SPN    1816     2024

In [44]:
lista_original = df_tabla_final.columns.tolist()
lista_nueva = ['year_win','team','statenme']
df_tabla_final = df_tabla_final.rename(columns=dict(zip(lista_original, lista_nueva)))
df_tabla_final.head()

   year_win                  team      statenme stateabb  styear  endyear
0      1958         A. S. K. Riga  Soviet Union      URS    1952     1988
1      1959         A. S. K. Riga  Soviet Union      URS    1952     1988
2      1960         P. B. K. CSKA  Soviet Union      URS    1952     1988
3      1961  B. C. Dinamo Tbilisi  Soviet Union      URS    1952     1988
4      1962         P. B. K. CSKA  Soviet Union      URS    1952     1988

In [45]:
df_tabla_final.to_csv("Copa_Europa_Euroleague.csv", index=False, encoding="utf-8")